sudo: required
language: node_js
node_js: '0.10'

services:
  - docker

branches:
  only:
  - master

before_install:
  - docker build --rm --tag=hmda/loader .
  - docker pull elasticsearch
  - docker run -d -p 9200:9200 -p 9300:9300 elasticsearch

before_script:
  - sleep 10

script:
  - docker run --rm -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" hmda/loader npm test
