language: node_js
node_js: '0.10'
services: elasticsearch
branches:
  only:
  - master
  - verify
before_install:
- sudo add-apt-repository ppa:ubuntugis/ppa -y
- sudo apt-get update -q
- sudo apt-get install -y libgdal-dev gdal-bin
