sudo: required
language: node_js
node_js: '0.10'

services:
  - docker

branches:
  only:
  - master

before_install:
  - docker build --rm --tag=hmda/loader .
  - ./build/start_elasticsearch.sh
  - sleep 10

script:
  - docker run --rm -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" hmda/loader npm test -- -h "$ES_HOST"
